
export const potentialGame = {
    // 'a8': 'black_rook',
    // 'b8': 'black_knight',
    // 'c8': 'black_bishop',
    // 'd8': 'black_queen',
    // 'e8': 'black_king',
    // 'c3': 'black_bishop',
    // 'd3': 'black_knight',
    // 'h8': 'black_rook',
    // 'a7': 'black_pawn',
    'b8': 'black_pawn',
    'c8': 'black_pawn',
    'd8': 'black_pawn',
    'e8': 'black_pawn',
    'f8': 'black_pawn',
    // 'g7': 'black_pawn',
    // 'h7': 'black_pawn',

    'a1': 'white_rook',
    'b1': 'white_knight',
    'c1': 'white_bishop',
    'd1': 'white_queen',
    'e1': 'white_king',
    'f1': 'white_bishop',
    'g1': 'white_knight',
    'h1': 'white_rook',
    
    'a7': 'white_pawn',
    'b7': 'white_pawn',
    'c7': 'white_pawn',
    'd7': 'white_pawn',
    'e7': 'white_pawn',
    'g8': 'white_pawn',
    'g7': 'white_pawn',
    'h7': 'white_pawn',
}